// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

// Component switches (default: enabled)
#ifndef OPENDTU_FEATURE_WEBAPP
#define OPENDTU_FEATURE_WEBAPP 1
#endif

#ifndef OPENDTU_FEATURE_DISPLAY
#define OPENDTU_FEATURE_DISPLAY 1
#endif

#ifndef OPENDTU_FEATURE_MQTT_HASS
#define OPENDTU_FEATURE_MQTT_HASS 1
#endif

#ifndef OPENDTU_FEATURE_MQTT_TLS_CERTINFO
#define OPENDTU_FEATURE_MQTT_TLS_CERTINFO 1
#endif

#ifndef OPENDTU_FEATURE_WEBAPI_PROMETHEUS
#define OPENDTU_FEATURE_WEBAPI_PROMETHEUS 1
#endif

#ifndef OPENDTU_FEATURE_WEBAPI_DEVICE
#define OPENDTU_FEATURE_WEBAPI_DEVICE 1
#endif

#ifndef OPENDTU_FEATURE_WEBAPI_MQTT
#define OPENDTU_FEATURE_WEBAPI_MQTT 1
#endif

#ifndef OPENDTU_FEATURE_WEBAPI_NETWORK
#define OPENDTU_FEATURE_WEBAPI_NETWORK 1
#endif

#ifndef OPENDTU_FEATURE_WEBAPI_NTP
#define OPENDTU_FEATURE_WEBAPI_NTP 1
#endif

#ifndef OPENDTU_FEATURE_BATTERY
#define OPENDTU_FEATURE_BATTERY 1
#endif

#ifndef OPENDTU_FEATURE_POWERMETER
#define OPENDTU_FEATURE_POWERMETER 1
#endif

#ifndef OPENDTU_FEATURE_SOLARCHARGER
#define OPENDTU_FEATURE_SOLARCHARGER 1
#endif

#ifndef OPENDTU_FEATURE_GRIDCHARGER
#define OPENDTU_FEATURE_GRIDCHARGER 1
#endif

#ifndef OPENDTU_FEATURE_POWERLIMITER
#define OPENDTU_FEATURE_POWERLIMITER 1
#endif

// Power meter provider switches
#if OPENDTU_FEATURE_POWERMETER
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_MQTT
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_MQTT 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_SDM
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SDM 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_JSON
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_JSON 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_SERIAL_SML
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SERIAL_SML 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_SMAHM2
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SMAHM2 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_SML
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_SML 1
    #endif
    #ifndef OPENDTU_FEATURE_POWERMETER_PROVIDER_MODBUS_UDP_VICTRON
        #define OPENDTU_FEATURE_POWERMETER_PROVIDER_MODBUS_UDP_VICTRON 1
    #endif
#else
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_MQTT
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_SDM
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_JSON
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_SERIAL_SML
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_SMAHM2
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_SML
    #undef OPENDTU_FEATURE_POWERMETER_PROVIDER_MODBUS_UDP_VICTRON
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_MQTT 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SDM 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_JSON 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SERIAL_SML 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_SMAHM2 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_HTTP_SML 0
    #define OPENDTU_FEATURE_POWERMETER_PROVIDER_MODBUS_UDP_VICTRON 0
#endif

// Battery provider switches
#if OPENDTU_FEATURE_BATTERY
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_PYLONTECH
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_PYLONTECH 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_JKBMS
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_JKBMS 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_MQTT
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_MQTT 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_VICTRON_SMARTSHUNT
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_VICTRON_SMARTSHUNT 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_PYTES
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_PYTES 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_SBS
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_SBS 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_JBDBMS
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_JBDBMS 1
    #endif
    #ifndef OPENDTU_FEATURE_BATTERY_PROVIDER_ZENDURE
        #define OPENDTU_FEATURE_BATTERY_PROVIDER_ZENDURE 1
    #endif
#else
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_PYLONTECH
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_JKBMS
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_MQTT
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_VICTRON_SMARTSHUNT
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_PYTES
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_SBS
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_JBDBMS
    #undef OPENDTU_FEATURE_BATTERY_PROVIDER_ZENDURE
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_PYLONTECH 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_JKBMS 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_MQTT 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_VICTRON_SMARTSHUNT 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_PYTES 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_SBS 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_JBDBMS 0
    #define OPENDTU_FEATURE_BATTERY_PROVIDER_ZENDURE 0
#endif

// Solar charger provider switches
#if OPENDTU_FEATURE_SOLARCHARGER
    #ifndef OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_VEDIRECT
        #define OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_VEDIRECT 1
    #endif
    #ifndef OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_MQTT
        #define OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_MQTT 1
    #endif
#else
    #undef OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_VEDIRECT
    #undef OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_MQTT
    #define OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_VEDIRECT 0
    #define OPENDTU_FEATURE_SOLARCHARGER_PROVIDER_MQTT 0
#endif

// Grid charger provider switches
#if OPENDTU_FEATURE_GRIDCHARGER
    #ifndef OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_HUAWEI
        #define OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_HUAWEI 1
    #endif
    #ifndef OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_TRUCKI
        #define OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_TRUCKI 1
    #endif
#else
    #undef OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_HUAWEI
    #undef OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_TRUCKI
    #define OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_HUAWEI 0
    #define OPENDTU_FEATURE_GRIDCHARGER_PROVIDER_TRUCKI 0
#endif
